Dev merge to master, PR (#3638)
* Adding plugin support (#2679)

* Adding plugin support

* Adding an empty __init__.py

* Moving the base task to the project root (#2702)

* Moving the base task to the project root

* Moving the base class more

* Changing the import again

* Adding a heartbeat to the analytics (#2709)

* Adding a heartbeat to the analytics

* Heartbeat every 30 seconds, not every 5

* Don't double track clients

* Fix 'local variable 'bot' referenced before assignment'

* Providing an error if tasks don't work for the given api (#2732)

* Fix for utf8 encoding when catching lured pokemon (#2720)

* Fixing lure pokestop encoding

* fixing lure encoding

* Fix For catchable not being displayed on the web (#2719)

* Fix For catchable not being displayed on the web

* Update catch_visible_pokemon.py

* Added encrypt.so compilation process to Dockerfile (#2695)

* OS Detection for encrypt lib (#2768)

Fix 32bit check, darwin and linux use the same file

Make it a function

Check if file exists, if not show error

Define file_name first

Fix return

Check if file exists, if not show error

Print info about paths

Fix for 32/64bit detection

* Fix Typo in unexpected_response_retry (#2531)

fixes #2525 #2523

* Revert "changing license from MIT to GPLv3"

This reverts commit 69fb64f2bf7c12e28c2bb6d2b636c6af55822448.

* When the google analytics domain is blocked the bot crashed. (#2764)

With a simple try / except this can be solved.

Fix dirty catch all

* Fixes #2698 - Prevents "Possibly searching too often" error after re-login. (#2771)

* Fixes #2698
- Added api.activate_signature call to prevent issue after re-login.
- Also replaced deprecated log call with event_manager emit to prevent exception being thrown.

* Modified to use OS detected library path as per PR #2768

* Support loading plugins from .zip files (#2766)

* Keep track of how many pokemon released (#2884)

* Setting Library path to work with encrypt.so (#2899)

Setting LD_LIBRARY_PATH on Dockerfile

* :sparkles: Added login and username to available stats (#2494)

Added a player_data property in PokemonGoBot to access player data from outside
Added unit tests for login and username stats
Added tests for call args when updating the window title
Added a platform-specific test for window title updating on win32 platform

* [dev] small fixes (#2912)

* Fixed emit_event typo

* Update CONTRIBUTORS.md

* Changed initialization location for "bot"

We use bot in main exception on 128

* Update pokecli.py

* Rename load_path to load_plugin (#2947)

* Adding some logic for pulling plugins from github (#2967)

* flush after title update (#2977)

* correctly re-raise exception to keep backtrace (#2944)

* Update MoveToMapPokemon to use events instead of logger. (#2913)

* Config/encrypt.so (#2964)

* Add config option for libencrypt.so

* Correctly set the config value and check for the file in said dir

* Fixed mispelling for "formatted" variable (#2984)

* Loading plugins from Github (#2992)

* Checking github plugin file existence

* Loading plugins from github

* Fixed #3000 (#3003)

Fixed syntax error on "move_to_map_pokemon.py" that makes the client crash when using this feature.

* Added MaxPotion inventory count to summary. (#3015)

Short Description: 
The Max Potion count was missing from the inventory summary.

Was #2456

* Added cleanup of download and files for encrypt.so after they are no longer needed (#3011)

* Fix bot not returning back after telepoting (#3014)

* Fix typo: last_long -> last_lon

* Whitespace cleanup

* Fix bug introduced by #3037: bot not returning back

* Fix Dockerfile installation (#3057)

* Fix for #3045 (#3055)

* Added request to check configuration (#3089)

* Fixed Dockerfile - missing \ on command lines (#3096)

* Fixed mispelling for "formatted" variable

* Docker commands missing trailing \

* Fix for FileIO slowing bot performance.This puts the map writing into a thread and makes sure it only executes  once. (#3100)

* Change word usage: "fled" to "escaped" (#3118)

"fled" is confusing to lot of people and is easily confused with pokemon vanishing. "escaped" is a better term.

* Update the example config file (#3120)

* Add config option for libencrypt.so

* Add config option for libencrypt.so

* Add config option for libencrypt.so

* Add config option for libencrypt.so

* Rename path.example.json to path.json.example

* typo: logrmation -> information (#2601)

Fix a typo. 

I assume that it was "information" initially, but became "logrmation" when someone used replace all functionality to replace all infos with logs. But I might be totally wrong at this point, idk. Just didn't like the word and wanted to fix that typo.

* Change fled to escaped (#3129)

Fix an issue after PR #3118

* When JSON parsing fails, give a rough indication of why (#3137)

* When JSON parsing fails, give a rough indication of why

* Use the official package instead of SHA1 commit

* Handle Github Download Zip Format (#3108)

* Checking github plugin file existence

* Loading plugins from github

* Starting install code for github plugins

* Updating GithubPlugin to support extracting folders

* Handling github zip formats by extracting to the correct location

* Refactor catch worker (#2527)

* refactor catch worker

* fix

* few renames

* add to contributors

* fix

* add missing behavior

* fix encounter events

* don't make events about ignored pokemon

* Added Run-Loop (#3143)

* Add files via upload

modified run script wich let you run the boot in a loop(if it crashes it restarts)

* Integreated Loop into run.sh

modified run.sh to loop the script so that even if it crashes it
automaticly restarts.

* fixing loop in spin fort task (#3165)

* Some love for the vim users (#3154)

* Updated README with link to desktop version (#3208)

* Fix for #3190 (#3197)

* MoveToMap: Add minimum balls to run (#3166)

* added config to ignore item count for Spin and MoveToFort (#3160)

* [Inventory Management] Add a central class for caching/parsing inventory & static data (#2528)

* new class to centralize inventory management

* use new inventory class in evolve_pokemon

* use new inventory to display # candy after catch

* Keeping a cache of gym information (#3236)

* New Option: "dont_nickname_favorite" (#2496)

* New Option: "dont_nickname_favorite"

This change (line 19) adds the option, that the user can choose, whether their favorite pokemons should also get a new nickname or not.

If a user want this, then he or she has to add the line ("dont_nickname_favorite" = true) after ("nickname_template": " ... ",).

* Update nickname_pokemon.py

* Update

* Put change to line 30

This reduce the reduce the runtime, because favorite pokemon won't be added to the list.

* Restart the loop when catching pokemon and there are more to catch (#3242)

* fixed NameError: global name 'pokemon_name' is not defined (#3244)

resolves ```traceback (most recent call last):
  File "pokecli.py", line 521, in <module>
    main()
  File "pokecli.py", line 95, in main
    bot.tick()
  File "/usr/src/app/pokemongo_bot/__init__.py", line 451, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/usr/src/app/pokemongo_bot/cell_workers/evolve_pokemon.py", line 38, in work
    self._execute_pokemon_evolve(pokemon, cache)
  File "/usr/src/app/pokemongo_bot/cell_workers/evolve_pokemon.py", line 117, in _execute_pokemon_evolve
    cache[pokemon.name] = 1
NameError: global name 'pokemon_name' is not defined```

* Stop fetching gym details (#3245)

* Checking all forts for lured pokemon (#3163)

* Fix flooding of keep_best_release (#3223)

* Fix flooding of keep_best_release

* Fix flooding of keep_best_release

* [Feature] Recycle Threshold (#2465)

* Add Threshold Option

* Add Threshold Option to Example Configs

* Add Name to Contributors

* Change config name and message

* Remove logger

* Add option to run when storage less than something

* Change Message

* Fix

* Error fixes, message improvement

* Config Changes and Remove Option

* Call heartbeat on step_walker even if speed is higher than distance (#2513)

* Return an empty list if no pokemon are available. (#3259)

The changes introduced in 4c95259 expose this bug.

* Allow UpdateTitleStats to emit events instead of rewriting the console (#3264)

* Updating our issue and PR templates to be more helpful (#3262)

* Dev (#3277)

* * adding enhanced sniping capabilities for move_to_map_pokemon

* Adding enhanced sniping capabilities for move_to_map_pokemon

* Update pgoapi to a newer version (#3241)

This should hopefully fix issues like #3181, #3098, #2874 and
potentially more.

Needs testing/verification. I am running now, but it does take about an
hour to trigger.

* Fix unexpected egg incubation retry (#3276)

incubator['used'] flag is set but not used in IncubateEggs._apply_incubators

* has_next_evolution is a function not a property (#3284)

* Powerful setup.sh (#3263)

* Rewrite run.sh

Very powerful run.sh with lots of function.
1.install(make .so)
2.update
3.config generator
4.config backup
5.run loop make it never down

It should run like 
run.sh *.json or other opinion. 
See -help.

* Update run.sh

* Update run.sh

OK problem solved

* Delete setup.py

* Rename run.sh to setup.sh

* Create run.sh

* Update setup.sh

* Update install.sh

* Update setup.sh

* Update run.sh

* Update setup.sh

Some small fix.

* Added +x to run.sh

* Added a configuration option "path_startmode" (conflict merge #2489) (#3270)

* Upstream update and merge, with path_startmode configuration

* Removed logger and fixed base task path

* As per request, path_startmode is now path_start_mode

* Removed all logging

* Adding documentation for how to use and write plugins (#3254)

* Adding documentation for how to use and write plugins

* Adding a link to the plugins docs in the Readme

* Updating link to the plugin docs in the readme

* Checking config file exists in run.sh (#3326)

* Improve and update pokemon.json (#3331)

1. Unminify for simplier edits
2. Add BaseAttack, BaseDefense, BaseStamina, CaptureRate, FleeRate, Fast/Special Attack(s)

* Made paths to .json files absolute so pokecli.py can be called from CRON (#3157)

* Made paths to .json files absolute so pokecli.py can be called from CRON

* made file paths abs in inventory

fixed incorrect dict reference, changed to .get() as felt this was intended

* Add fast & charged moves data from #2117 (originally by @iananass) (#3336)

Data for pokemon quick & slow attacks

* Upgrade pgoapi to the b4bf0e089dfe09903f8dda37dae56910e01f94cc commit(latest for now). (#3337)

* Revert "Upgrade pgoapi to the b4bf0e089dfe09903f8dda37dae56910e01f94cc commit…" (#3340)

* Added map_path configuration for move_to_map. (#3339)

* Log stats on terminal (#3312)

* added _log_on_terminal function

* Added logic to toggle terminal logging functionality from config file

* Added possibility to disable title changes, refactor code

* Refactor tuples

* Refactor ifs to clearer syntax

* changes to improve event system based on new web ui devs requests

* typo :D

* let's use dict.get a bit to avoid errors

* keeping the account in the remote command response

* Add ColoredLoggingHandler (#3198)

* Update TransferPokemon to use new Inventory Class (#3320)

* Update TransferPokemon to use new Inventory Class

* Use base_dir

* Don't release pokemon if bot is on test mode

* Some text fixes for setup.sh (#3390)

Minor text fix.

* Fix path of shells in install.sh (#3393)

* Update install.sh

Fix path

* Update setup.sh

fix path

* Update run.sh

fix path

* Fix evolution error in pokemon.json (#3344)

Fix evolution error in pokemon.json

* Improve formatting consistency in transfer_pokemon.py (#3397)

Improve formatting consistency

* Remove unnecessary file

* Put info on the next line in run.sh (#3422)

* Update setup.sh

fix typo

* Update run.sh

fix typo

* Fix Struct() argument 1 must be string, not unicode. (#3375)

* Give the possibility to disable a task without removing it (#3417)

* Give the possiblity to disable a task in config without removing it from the config file

* Put exmple only in nickname task

* Add Unit testing

* typo

* Use enabled false as exemple

* fix config creation (#3482)

Changed auth to be more specifik and added right permissions.

* Remove unused IV calculation from evolve_pokemon (#3487)

Previously IV was computed in each worker. Now its fetched from inventory. This was left over and not called in the worker at all.

* Don't show Inventory full event if we set "ignore_item_count" (#3440)

* Fix showing the date in run.sh (#3433)

fix the logic of showing the date

* Typo fix: show new catch rate after berry throw. (#3521)

* Fix stdout is not a terminal (#3511)

* Ensure recycling happens if bag is over capacity. (#3531)

Short Description:
Ensures you that item Recycling happens if you have more items than the total bag capacity.

When you level up, you are awarded items which can cause the bag to be over the capacity.

* Better inventory:  attacks & movesets,  IV CP perfection,  pokemon level,  etc.. (#3455)

* Add "level to CP multiplier" data

Data is from justinleewells/pogo-optimizer:
https://github.com/justinleewells/pogo-optimizer/blob/edd692d/data/game/level-to-cpm.json

* Many improvements & additions for the inventory logic

 - LevelToCPm, FastAttacks, ChargedAttacks, Movesets
 - More info for each pokemon:  attacks data,  percent to max cp,  IV CP perfection

* Add PyCharm/IDEA *.iml (project file) to ignored

* Fixes, improvements & refactoring for inventory.py

 - Return inadvertently deleted pieces of code (thanks to @achretien)
 - Evolution logic fixes
 - Other minor fixes
 - Moveset logic moved to Moveset class

* Fix data for pokemons & charged moves

* Inventory tests:  pokemon data,  LevelToCPm,  attacks

* Fix travis build

* Fix info for Hitmonlee & Hitmonchan

* Revert "Better inventory:  attacks & movesets,  IV CP perfection,  pokemon level,  etc.." (#3549)

* run.bat for windows (#3542)

run.bat with persistent loop

* Fix error when MoveToFort called from handle_soft_ban.py (#3500)

* Fix error when MoveToFort called from handle_soft_ban.py

* Added myself to CONTRIBUTORS.md

* Fixed list of charged attacks for Venonat (#3548) + BaseDefense/BaseStamina info fix (#3550)

* Revert "Revert "Better inventory:  attacks & movesets,  IV CP perfection,  pokemon level,  etc.." (#3549)"

This reverts commit e9b229ec0fd14a4814ea7431b1256850e907cfbf.

* Fix BaseDefense/BaseStamina and type info

Fixed BaseDefense/BaseStamina info (was mixed up)
Fixed type info for Mr. Mime, Clefairy, Clefable, Jigglypuff, Wigglytuff
Added check for correctness of exact CP value calculation

* Fixed list of charged attacks for Venonat

* Don't kill bot in case of unexpected moveset, use fallback + better error message

* Blacklisting tejado from getting mentioned by the mention-bot

* Moving wiki pages to docs folder

* UpdateTitleStats -> UpdateLiveStats, new stat, refactoring (#3467)

* Renamed UpdateTitleStats to UpdateLiveStats

* Cleaned worker documentation
* Added documentation for terminal_log and terminal_title
* Fixed https://github.com/PokemonGoF/PokemonGo-Bot/pull/3312#issuecomment-238672978
* Made some refactoring
* Added captures_per_hour stat that shows estimated pokemon captures per hour
* Added a captures_per_hour method in metrics.py
* Added unit tests for features added in https://github.com/PokemonGoF/PokemonGo-Bot/pull/3312
* Added unit tests for captures_per_hour

* Avoid useless overhead when no output configured

* Added default config values in documentation

* Fixed issue with title updating on Windows

* See https://github.com/PokemonGoF/PokemonGo-Bot/pull/3472

* Update installation docs to reflect setup sh changes (#3567)

* Fixed chmod in setup.sh (#3565)

* forgot to include the config location

* fixed setup files

* Updated readme to have better readability (#3569)

* Made the READ me more read friendly and compactor.

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update faq.md

* More documentation changes making it noob proof(er) (#3575)

* added information on what what does

* add a link to the docker hub for NAS users.

* Update Readme to point to the latest wiki and documentation (#3579)

* Improve Docker Image and `docker-compose.yml` (#3583)

- Use the non-`onbuild` variant of the python base image to better make use of Docker image caching
 - Update some volumes in `docker-compose.yml` for pogoweb

* Small fixes and improvments in setup.sh (#3585)

Adding -p to mkdir - it will not show "already exist folder" error.
And adding to backup *gpx and path files.

* Remove the "evolve_captured" flag in favor of the EvolveTask (#3530)

* Remove the "evolve_captured" flag in favor of the EvolveTask

* Remove unused event

* Warn the user instead of stopping the bot

* Improved documentation (#3604)

- Improved read flow
- Added volume sharing of cache folder

* Update installation.md (#3618)

* Update installation.md

Changed the linux Section and the Ubuntu example, for easyer access
(if anyone now how to make a code block collapsable feel free)

* Update installation.md

removed pastebin link (cause i put it there in the first place) because it's not needed
edittet linux section to Installation Linux on the example of Ubuntu (merged it with ubuntu install section)

i hope i didn't miss anything

will check on mac and windows in the next 24h. I will make a new pr for that and link it here

* moving_to_fort and moving_to_lured_fort now also emit current_position (#3614)

arrived_at_fort emits position

* Fix handle soft ban (#3629)

* Fix `MoveToFort.config` None to Empty {} dict

Whenever the bot ticks, `config.get('enable', True)` is required

* Add new contributor

* [config] new tasks in example files (#3457)

* add UpdateTitleStats to config examples

* add UpdateTitleStats to config examples

* add SleepSchedule to config examples

all config files are missing SleepSchedule from task
see https://github.com/PokemonGoF/PokemonGo-Bot/pokemongo_bot/cell_workers/sleep_schedule.py for more info
,
      {
        "type": "SleepSchedule",
        "config": {
          "time": "22:54",
          "duration":"7:46",
          "time_random_offset": "00:24",
          "duration_random_offset": "00:43"
        }
      },

* Forgot one

* fix for changes in #3467

* disable new tasks by default, removed duplicate